# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev8+g540b695.d20230413'
__version_tuple__ = version_tuple = (0, 1, 'dev8', 'g540b695.d20230413')
