name: Mirror to Gitee Repo

on: [ push, delete, create ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    if: github.repository_owner == 'ICCMS-CALYPSO'
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          ORGANIZATION: ICCMS-CALYPSO
          SSH_PRIVATE_KEY: ${{ secrets.SYNC_GITEE_PRIVATE_KEY }}
        with:
          source-repo: "https://github.com/ICCMS-CALYPSO/CALYPSO-Bohrium.git"
          destination-repo: "git@gitee.com:iccms-calypso/calypso-bohrium.git"
